parrafos = ARGV[0].to_i

if parrafos == 1
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.
    "    
elsif parrafos == 2
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet eros ipsum. Proin dapibus purus ac dolor sodales sodales. Duis rhoncus ligula id elit bibendum mollis. Cras at magna id quam auctor laoreet. Donec ornare neque ut lacus luctus tincidunt. Cras rutrum tellus quis eros maximus, et rutrum tortor sollicitudin. Sed eget iaculis orci.
    "
elsif parrafos == 3
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet eros ipsum. Proin dapibus purus ac dolor sodales sodales. Duis rhoncus ligula id elit bibendum mollis. Cras at magna id quam auctor laoreet. Donec ornare neque ut lacus luctus tincidunt. Cras rutrum tellus quis eros maximus, et rutrum tortor sollicitudin. Sed eget iaculis orci.
    
    Aenean faucibus iaculis sem eget blandit. Suspendisse faucibus sem nec tincidunt tincidunt. Nulla gravida consequat rhoncus. Vestibulum nec egestas risus. Nam id dolor eros. Donec nec neque quam. Cras vel sodales nisl. Vestibulum eu dui sit amet sem aliquet malesuada a sit amet felis. Morbi tristique, dui viverra rutrum vehicula, mi enim mollis mi, rutrum iaculis lectus magna eu enim. Sed ultrices, dui quis fermentum consectetur, metus turpis fringilla neque, id tempor nisi mi eget dui. Aenean malesuada arcu eu nisi dapibus iaculis. Vestibulum fermentum purus eget nisl semper gravida. Nam gravida tellus sit amet arcu malesuada, eu ultrices turpis ullamcorper.
    "
elsif parrafos == 4
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet eros ipsum. Proin dapibus purus ac dolor sodales sodales. Duis rhoncus ligula id elit bibendum mollis. Cras at magna id quam auctor laoreet. Donec ornare neque ut lacus luctus tincidunt. Cras rutrum tellus quis eros maximus, et rutrum tortor sollicitudin. Sed eget iaculis orci.
    
    Aenean faucibus iaculis sem eget blandit. Suspendisse faucibus sem nec tincidunt tincidunt. Nulla gravida consequat rhoncus. Vestibulum nec egestas risus. Nam id dolor eros. Donec nec neque quam. Cras vel sodales nisl. Vestibulum eu dui sit amet sem aliquet malesuada a sit amet felis. Morbi tristique, dui viverra rutrum vehicula, mi enim mollis mi, rutrum iaculis lectus magna eu enim. Sed ultrices, dui quis fermentum consectetur, metus turpis fringilla neque, id tempor nisi mi eget dui. Aenean malesuada arcu eu nisi dapibus iaculis. Vestibulum fermentum purus eget nisl semper gravida. Nam gravida tellus sit amet arcu malesuada, eu ultrices turpis ullamcorper.
    
    Pellentesque laoreet velit non erat pharetra blandit. Donec tincidunt malesuada aliquam. Nam varius at erat bibendum dictum. Nulla pulvinar ante in velit feugiat malesuada. Proin dignissim mi ut neque dignissim molestie tincidunt in augue. Sed egestas quis massa non tincidunt. Ut a arcu iaculis, malesuada urna a, consequat libero. Ut at magna et augue convallis suscipit ut sed nibh. Ut dignissim nisl eget libero auctor egestas. Sed vestibulum et lorem et scelerisque. Pellentesque consequat dui sed neque dignissim mollis. Aliquam non sodales dolor. Aenean egestas gravida enim, a fermentum leo consequat eget. Nam placerat quis nunc vel iaculis. Nam nibh tellus, mollis non lectus at, malesuada placerat turpis.
    "
else
    puts "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet eros ipsum. Proin dapibus purus ac dolor sodales sodales. Duis rhoncus ligula id elit bibendum mollis. Cras at magna id quam auctor laoreet. Donec ornare neque ut lacus luctus tincidunt. Cras rutrum tellus quis eros maximus, et rutrum tortor sollicitudin. Sed eget iaculis orci.
    
    Aenean faucibus iaculis sem eget blandit. Suspendisse faucibus sem nec tincidunt tincidunt. Nulla gravida consequat rhoncus. Vestibulum nec egestas risus. Nam id dolor eros. Donec nec neque quam. Cras vel sodales nisl. Vestibulum eu dui sit amet sem aliquet malesuada a sit amet felis. Morbi tristique, dui viverra rutrum vehicula, mi enim mollis mi, rutrum iaculis lectus magna eu enim. Sed ultrices, dui quis fermentum consectetur, metus turpis fringilla neque, id tempor nisi mi eget dui. Aenean malesuada arcu eu nisi dapibus iaculis. Vestibulum fermentum purus eget nisl semper gravida. Nam gravida tellus sit amet arcu malesuada, eu ultrices turpis ullamcorper.
    
    Pellentesque laoreet velit non erat pharetra blandit. Donec tincidunt malesuada aliquam. Nam varius at erat bibendum dictum. Nulla pulvinar ante in velit feugiat malesuada. Proin dignissim mi ut neque dignissim molestie tincidunt in augue. Sed egestas quis massa non tincidunt. Ut a arcu iaculis, malesuada urna a, consequat libero. Ut at magna et augue convallis suscipit ut sed nibh. Ut dignissim nisl eget libero auctor egestas. Sed vestibulum et lorem et scelerisque. Pellentesque consequat dui sed neque dignissim mollis. Aliquam non sodales dolor. Aenean egestas gravida enim, a fermentum leo consequat eget. Nam placerat quis nunc vel iaculis. Nam nibh tellus, mollis non lectus at, malesuada placerat turpis.
    
    Sed in turpis vel lacus ornare commodo. Sed dolor ipsum, viverra et varius vel, interdum et nisi. Morbi tempor ac lacus ac tempor. Morbi eget sapien vel turpis varius tristique. Integer euismod neque ut venenatis blandit. Aliquam sit amet fermentum neque. Nulla suscipit neque vel neque ullamcorper pellentesque. Donec a lobortis orci, tempus accumsan elit."
end
# Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo finibus ex nec blandit. Nullam pellentesque molestie tempor. Nunc quam neque, aliquet id nisl et, euismod hendrerit mauris. Praesent pharetra, nibh eu laoreet porttitor, dolor eros tincidunt urna, ac ultricies nisi lectus et turpis. Integer ultricies sem risus, non pretium libero elementum at. Morbi facilisis dictum lorem vel porta. Suspendisse diam quam, tincidunt non dolor vel, suscipit luctus ante. Praesent laoreet imperdiet arcu eget blandit. Pellentesque efficitur hendrerit purus non malesuada. Cras molestie tempor ornare. Donec ut ullamcorper magna. Duis odio eros, semper vulputate enim eget, malesuada ornare ante.

# Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet eros ipsum. Proin dapibus purus ac dolor sodales sodales. Duis rhoncus ligula id elit bibendum mollis. Cras at magna id quam auctor laoreet. Donec ornare neque ut lacus luctus tincidunt. Cras rutrum tellus quis eros maximus, et rutrum tortor sollicitudin. Sed eget iaculis orci.

# Aenean faucibus iaculis sem eget blandit. Suspendisse faucibus sem nec tincidunt tincidunt. Nulla gravida consequat rhoncus. Vestibulum nec egestas risus. Nam id dolor eros. Donec nec neque quam. Cras vel sodales nisl. Vestibulum eu dui sit amet sem aliquet malesuada a sit amet felis. Morbi tristique, dui viverra rutrum vehicula, mi enim mollis mi, rutrum iaculis lectus magna eu enim. Sed ultrices, dui quis fermentum consectetur, metus turpis fringilla neque, id tempor nisi mi eget dui. Aenean malesuada arcu eu nisi dapibus iaculis. Vestibulum fermentum purus eget nisl semper gravida. Nam gravida tellus sit amet arcu malesuada, eu ultrices turpis ullamcorper.

# Pellentesque laoreet velit non erat pharetra blandit. Donec tincidunt malesuada aliquam. Nam varius at erat bibendum dictum. Nulla pulvinar ante in velit feugiat malesuada. Proin dignissim mi ut neque dignissim molestie tincidunt in augue. Sed egestas quis massa non tincidunt. Ut a arcu iaculis, malesuada urna a, consequat libero. Ut at magna et augue convallis suscipit ut sed nibh. Ut dignissim nisl eget libero auctor egestas. Sed vestibulum et lorem et scelerisque. Pellentesque consequat dui sed neque dignissim mollis. Aliquam non sodales dolor. Aenean egestas gravida enim, a fermentum leo consequat eget. Nam placerat quis nunc vel iaculis. Nam nibh tellus, mollis non lectus at, malesuada placerat turpis.

# Sed in turpis vel lacus ornare commodo. Sed dolor ipsum, viverra et varius vel, interdum et nisi. Morbi tempor ac lacus ac tempor. Morbi eget sapien vel turpis varius tristique. Integer euismod neque ut venenatis blandit. Aliquam sit amet fermentum neque. Nulla suscipit neque vel neque ullamcorper pellentesque. Donec a lobortis orci, tempus accumsan elit.